<?php

/**
 * @file
 * Install, update and uninstall functions for the Color Field Spectrum module.
 */

declare(strict_types=1);

/**
 * Implements hook_requirements().
 *
 * If the Spectrum library doesn't exist, show a warning on the status page.
 */
function color_field_widget_spectrum_requirements($phase): array {
  $requirements = [];

  if ($phase === 'runtime') {
    $requirements['color_field_widget_spectrum'] = !file_exists(DRUPAL_ROOT . '/libraries/spectrum/spectrum.js') ? [
      'title' => t('Color Field library: Spectrum'),
      'value' => t('Missing'),
      'description' => t('If you want to use the Spectrum widget, you must download the <a href=":url">Spectrum</a> Library and copy it to :library', [
        ':url' => 'https://github.com/bgrins/spectrum',
        ':library' => DRUPAL_ROOT . '/libraries/spectrum/',
      ]),
      'severity' => REQUIREMENT_WARNING,
    ] : [
      'title' => t('Color Field library: Spectrum'),
      'value' => t('Installed'),
      'severity' => REQUIREMENT_OK,
    ];
  }

  return $requirements;
}
