<?php

/**
 * @file
 * Module hooks implementations.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\bibcite_import\Hook\BibciteImportHooks;
use Drupal\bibcite_entity\Entity\ReferenceInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_bibcite_reference_prepare_form().
 *
 * Populate form values from tempstore.
 */
#[LegacyHook]
function bibcite_import_bibcite_reference_prepare_form(ReferenceInterface $entity, $operation, FormStateInterface $form_state) {
  \Drupal::service(BibciteImportHooks::class)->bibciteReferencePrepareForm($entity, $operation, $form_state);
}

/**
 * Implements hook_help().
 */
#[LegacyHook]
function bibcite_import_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service(BibciteImportHooks::class)->help($route_name, $route_match);
}
