content = open('/etc/nginx/sites-available/khartasia', 'w')
content.write('server {\n')
content.write('    server_name khartasia.org www.khartasia.org;\n')
content.write('    root /var/www/khartasia/web;\n')
content.write('    index index.php;\n')
content.write('    client_max_body_size 64M;\n')
content.write('    location / {\n')
content.write('        try_files $uri /index.php?$query_string;\n')
content.write('    }\n')
content.write('    location ~ \\.php$ {\n')
content.write('        fastcgi_pass unix:/run/php/php8.3-fpm.sock;\n')
content.write('        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;\n')
content.write('        include fastcgi_params;\n')
content.write('        fastcgi_read_timeout 300;\n')
content.write('    }\n')
content.write('    location ~ /\\. { deny all; }\n')
content.write('    location /vendor { deny all; }\n')
content.write('    listen 80;\n')
content.write('    listen [::]:80;\n')
content.write('}\n')
content.close()
print('OK')
