<?php

/**
 * @file
 * Contains ui_patterns_views.install.
 */

declare(strict_types=1);

use Drupal\Core\Update\UpdateHookRegistry;

/**
 * Implements hook_update_last_removed().
 */
function ui_patterns_views_update_last_removed(): int {
  $currentInstalledVersion = Drupal::service(UpdateHookRegistry::class)
    ->getInstalledVersion('ui_patterns_views');
  if ($currentInstalledVersion >= 9101) {
    // The update in 1.x with the try to merge ui_patterns_views_style.
    return 9101;
  }
  return 0;
}
