<?php

/**
 * @file
 * Module hooks.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\bibcite_endnote\Hook\BibciteEndnoteHooks;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
#[LegacyHook]
function bibcite_endnote_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service(BibciteEndnoteHooks::class)->help($route_name, $route_match);
}
